<?php

/**
 * @package CRM
 *
 * Generated from contactinfo_dedupe/xml/schema/CRM/ContactinfoDedupe/DedupePriority.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 */

use CRM_ContactinfoDedupe_ExtensionUtil as E;

/**
 * Database access object for the DedupePriority entity.
 */
class CRM_ContactinfoDedupe_DAO_DedupePriority extends CRM_Core_DAO {

  const EXT = E::LONG_NAME;
  const TABLE_ADDED = '';

  /**
   * @var string
   */
  public static $_tableName = 'civicrm_contactinfo_dedupe_priority';

  /**
   * @var bool
   */
  public static $_log = TRUE;

  /**
   * Unique Priority ID
   * @var int|string|null
   */
  public $id;

  /**
   * FK to LocationType
   * @var int|string|null
   */
  public $location_type_id;

  /**
   * Priority rank (lower number = higher priority)
   * @var int|string
   */
  public $priority;

  public function __construct() {
    $this->__table = 'civicrm_contactinfo_dedupe_priority';
    parent::__construct();
  }

  public static function getEntityTitle($plural = FALSE) {
    return $plural ? E::ts('Dedupe Priorities') : E::ts('Dedupe Priority');
  }

  public static function getReferenceColumns() {
    if (!isset(Civi::$statics[__CLASS__]['links'])) {
      Civi::$statics[__CLASS__]['links'] = static::createReferenceColumns(__CLASS__);
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'location_type_id', 'civicrm_location_type', 'id');
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'links_callback', Civi::$statics[__CLASS__]['links']);
    }
    return Civi::$statics[__CLASS__]['links'];
  }

  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => E::ts('Unique Priority ID'),
          'required' => TRUE,
          'where' => 'civicrm_contactinfo_dedupe_priority.id',
          'table_name' => 'civicrm_contactinfo_dedupe_priority',
          'entity' => 'DedupePriority',
          'bao' => 'CRM_ContactinfoDedupe_DAO_DedupePriority',
          'localizable' => 0,
          'html' => ['type' => 'Number'],
          'readonly' => TRUE,
          'add' => NULL,
        ],
        'location_type_id' => [
          'name' => 'location_type_id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => E::ts('FK to LocationType'),
          'required' => TRUE,
          'where' => 'civicrm_contactinfo_dedupe_priority.location_type_id',
          'table_name' => 'civicrm_contactinfo_dedupe_priority',
          'entity' => 'DedupePriority',
          'bao' => 'CRM_ContactinfoDedupe_DAO_DedupePriority',
          'localizable' => 0,
          'FKClassName' => 'CRM_Core_DAO_LocationType',
          'add' => NULL,
        ],
        'priority' => [
          'name' => 'priority',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Priority'),
          'description' => E::ts('Priority rank (lower number = higher priority)'),
          'required' => TRUE,
          'where' => 'civicrm_contactinfo_dedupe_priority.priority',
          'default' => '0',
          'table_name' => 'civicrm_contactinfo_dedupe_priority',
          'entity' => 'DedupePriority',
          'bao' => 'CRM_ContactinfoDedupe_DAO_DedupePriority',
          'localizable' => 0,
          'html' => ['type' => 'Number'],
          'add' => NULL,
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  public static function &fieldKeys() {
    if (!isset(Civi::$statics[__CLASS__]['fieldKeys'])) {
      Civi::$statics[__CLASS__]['fieldKeys'] = array_flip(CRM_Utils_Array::collect('name', self::fields()));
    }
    return Civi::$statics[__CLASS__]['fieldKeys'];
  }

  public static function getTableName() {
    return self::$_tableName;
  }

  public function getLog() {
    return self::$_log;
  }

  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'contactinfo_dedupe_priority', $prefix, []);
    return $r;
  }

  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'contactinfo_dedupe_priority', $prefix, []);
    return $r;
  }

  public static function indices($localize = TRUE) {
    $indices = [
      'UI_location_type_id' => [
        'name' => 'UI_location_type_id',
        'field' => ['location_type_id'],
        'localizable' => FALSE,
        'unique' => TRUE,
        'sig' => 'civicrm_contactinfo_dedupe_priority::1::location_type_id',
      ],
      'UI_priority' => [
        'name' => 'UI_priority',
        'field' => ['priority'],
        'localizable' => FALSE,
        'unique' => TRUE,
        'sig' => 'civicrm_contactinfo_dedupe_priority::1::priority',
      ],
    ];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
