<?php

/**
 * @package CRM
 *
 * Generated from contactinfo_dedupe/xml/schema/CRM/ContactinfoDedupe/DedupeAuditLog.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 */

use CRM_ContactinfoDedupe_ExtensionUtil as E;

/**
 * Database access object for the DedupeAuditLog entity.
 */
class CRM_ContactinfoDedupe_DAO_DedupeAuditLog extends CRM_Core_DAO {

  const EXT = E::LONG_NAME;
  const TABLE_ADDED = '';

  /**
   * @var string
   */
  public static $_tableName = 'civicrm_contactinfo_dedupe_audit_log';

  /**
   * @var bool
   */
  public static $_log = TRUE;

  /**
   * @var int|string|null
   */
  public $id;

  /**
   * @var string
   */
  public $entity_type;

  /**
   * @var int|string|null
   */
  public $contact_id;

  /**
   * @var int|string|null
   */
  public $kept_entity_id;

  /**
   * @var int|string|null
   */
  public $removed_entity_id;

  /**
   * @var string
   */
  public $status;

  /**
   * @var string|null
   */
  public $field_changes;

  /**
   * @var string
   */
  public $created_date;

  /**
   * @var int|string|null
   */
  public $created_by;

  public function __construct() {
    $this->__table = 'civicrm_contactinfo_dedupe_audit_log';
    parent::__construct();
  }

  public static function getEntityTitle($plural = FALSE) {
    return $plural ? E::ts('Dedupe Audit Logs') : E::ts('Dedupe Audit Log');
  }

  public static function getReferenceColumns() {
    if (!isset(Civi::$statics[__CLASS__]['links'])) {
      Civi::$statics[__CLASS__]['links'] = static::createReferenceColumns(__CLASS__);
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'contact_id', 'civicrm_contact', 'id');
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'links_callback', Civi::$statics[__CLASS__]['links']);
    }
    return Civi::$statics[__CLASS__]['links'];
  }

  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => E::ts('Unique AuditLog ID'),
          'required' => TRUE,
          'where' => 'civicrm_contactinfo_dedupe_audit_log.id',
          'table_name' => 'civicrm_contactinfo_dedupe_audit_log',
          'entity' => 'DedupeAuditLog',
          'bao' => 'CRM_ContactinfoDedupe_DAO_DedupeAuditLog',
          'localizable' => 0,
          'html' => ['type' => 'Number'],
          'readonly' => TRUE,
          'add' => NULL,
        ],
        'entity_type' => [
          'name' => 'entity_type',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Entity Type'),
          'description' => E::ts('Entity type: address, email, or phone'),
          'required' => TRUE,
          'maxlength' => 32,
          'where' => 'civicrm_contactinfo_dedupe_audit_log.entity_type',
          'table_name' => 'civicrm_contactinfo_dedupe_audit_log',
          'entity' => 'DedupeAuditLog',
          'bao' => 'CRM_ContactinfoDedupe_DAO_DedupeAuditLog',
          'localizable' => 0,
          'add' => NULL,
        ],
        'contact_id' => [
          'name' => 'contact_id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => E::ts('FK to Contact'),
          'required' => TRUE,
          'where' => 'civicrm_contactinfo_dedupe_audit_log.contact_id',
          'table_name' => 'civicrm_contactinfo_dedupe_audit_log',
          'entity' => 'DedupeAuditLog',
          'bao' => 'CRM_ContactinfoDedupe_DAO_DedupeAuditLog',
          'localizable' => 0,
          'FKClassName' => 'CRM_Contact_DAO_Contact',
          'add' => NULL,
        ],
        'kept_entity_id' => [
          'name' => 'kept_entity_id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => E::ts('ID of the record that was kept'),
          'required' => TRUE,
          'where' => 'civicrm_contactinfo_dedupe_audit_log.kept_entity_id',
          'table_name' => 'civicrm_contactinfo_dedupe_audit_log',
          'entity' => 'DedupeAuditLog',
          'bao' => 'CRM_ContactinfoDedupe_DAO_DedupeAuditLog',
          'localizable' => 0,
          'add' => NULL,
        ],
        'removed_entity_id' => [
          'name' => 'removed_entity_id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => E::ts('ID of the record that was removed'),
          'required' => TRUE,
          'where' => 'civicrm_contactinfo_dedupe_audit_log.removed_entity_id',
          'table_name' => 'civicrm_contactinfo_dedupe_audit_log',
          'entity' => 'DedupeAuditLog',
          'bao' => 'CRM_ContactinfoDedupe_DAO_DedupeAuditLog',
          'localizable' => 0,
          'add' => NULL,
        ],
        'status' => [
          'name' => 'status',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Status'),
          'description' => E::ts('Status: changed or removed'),
          'required' => TRUE,
          'maxlength' => 16,
          'where' => 'civicrm_contactinfo_dedupe_audit_log.status',
          'table_name' => 'civicrm_contactinfo_dedupe_audit_log',
          'entity' => 'DedupeAuditLog',
          'bao' => 'CRM_ContactinfoDedupe_DAO_DedupeAuditLog',
          'localizable' => 0,
          'add' => NULL,
        ],
        'field_changes' => [
          'name' => 'field_changes',
          'type' => CRM_Utils_Type::T_TEXT,
          'title' => E::ts('Field Changes'),
          'description' => E::ts('JSON-encoded field changes'),
          'where' => 'civicrm_contactinfo_dedupe_audit_log.field_changes',
          'table_name' => 'civicrm_contactinfo_dedupe_audit_log',
          'entity' => 'DedupeAuditLog',
          'bao' => 'CRM_ContactinfoDedupe_DAO_DedupeAuditLog',
          'localizable' => 0,
          'add' => NULL,
        ],
        'created_date' => [
          'name' => 'created_date',
          'type' => CRM_Utils_Type::T_DATE + CRM_Utils_Type::T_TIME,
          'title' => E::ts('Created Date'),
          'description' => E::ts('When the action was performed'),
          'required' => TRUE,
          'where' => 'civicrm_contactinfo_dedupe_audit_log.created_date',
          'table_name' => 'civicrm_contactinfo_dedupe_audit_log',
          'entity' => 'DedupeAuditLog',
          'bao' => 'CRM_ContactinfoDedupe_DAO_DedupeAuditLog',
          'localizable' => 0,
          'add' => NULL,
        ],
        'created_by' => [
          'name' => 'created_by',
          'type' => CRM_Utils_Type::T_INT,
          'description' => E::ts('FK to Contact who performed the action'),
          'where' => 'civicrm_contactinfo_dedupe_audit_log.created_by',
          'table_name' => 'civicrm_contactinfo_dedupe_audit_log',
          'entity' => 'DedupeAuditLog',
          'bao' => 'CRM_ContactinfoDedupe_DAO_DedupeAuditLog',
          'localizable' => 0,
          'add' => NULL,
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  public static function &fieldKeys() {
    if (!isset(Civi::$statics[__CLASS__]['fieldKeys'])) {
      Civi::$statics[__CLASS__]['fieldKeys'] = array_flip(CRM_Utils_Array::collect('name', self::fields()));
    }
    return Civi::$statics[__CLASS__]['fieldKeys'];
  }

  public static function getTableName() {
    return self::$_tableName;
  }

  public function getLog() {
    return self::$_log;
  }

  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'contactinfo_dedupe_audit_log', $prefix, []);
    return $r;
  }

  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'contactinfo_dedupe_audit_log', $prefix, []);
    return $r;
  }

  public static function indices($localize = TRUE) {
    $indices = [
      'IX_entity_type' => [
        'name' => 'IX_entity_type',
        'field' => ['entity_type'],
        'localizable' => FALSE,
        'sig' => 'civicrm_contactinfo_dedupe_audit_log::0::entity_type',
      ],
      'IX_contact_id' => [
        'name' => 'IX_contact_id',
        'field' => ['contact_id'],
        'localizable' => FALSE,
        'sig' => 'civicrm_contactinfo_dedupe_audit_log::0::contact_id',
      ],
      'IX_created_date' => [
        'name' => 'IX_created_date',
        'field' => ['created_date'],
        'localizable' => FALSE,
        'sig' => 'civicrm_contactinfo_dedupe_audit_log::0::created_date',
      ],
    ];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
